version: "3"
services:
  postgres:
    container_name: 'database'
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432

  api:
    build: .
    container_name: api
    command: npm run dev
    volumes:
      - .:/code
    ports:
      - 3000:3000
    links:
      - postgres