version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run: npm install
      - run: npm run eslint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
